### PR TITLE
Add translations up to react-admin 3.14.1

### PR DESCRIPTION
**Pull request by kolben**

### CODE REVIEW

**Comment by kolben** [comment]
@Kladdy Would you have time to merge this?

**Comment by Kladdy** [comment]
Sure, great PR.

**Comment by Kladdy** [comment]
@kolben Would you like to get ownership of this repo for further changes?

**Comment by kolben** [comment]
@Kladdy That would be great. But more importantly the npm package. Would like to get it back to ra-language-swedish and retire @kolben/ra-language-swedish

I was a bit too trigger happy :(
https://github.com/marmelab/react-admin/pull/6156

**Comment by Kladdy** [comment]
@kolben You now have Admin rights for the npm-package and Github repo :-)

**Comment by kolben** [comment]
Thank you @Kladdy I'll try to sort it out in the coming days and get ra-language-swedish as the only npm package

**Pull request merged**
